In [1]:
import numpy as np

In [2]:
### ejercicio:
vector=[3,6,1,9,11]

In [3]:
##Matriz
matriz=[[1,3,4],[6,8,3],[0,5,3]]

In [4]:
matriz

[[1, 3, 4], [6, 8, 3], [0, 5, 3]]

In [7]:
##Ejercicio.
##Multiplicar la matriz por 2
matriz2=[]
for fila in matriz:
    print(fila)
    fila2=[]
    for elmen in fila:
        fila2.append(elmen*2)
    matriz2.append(fila2)
    

[1, 3, 4]
[6, 8, 3]
[0, 5, 3]


In [8]:
matriz2

[[2, 6, 8], [12, 16, 6], [0, 10, 6]]

In [9]:
2*matriz

[[1, 3, 4], [6, 8, 3], [0, 5, 3], [1, 3, 4], [6, 8, 3], [0, 5, 3]]

In [10]:
## Array de numpy

In [11]:
np_matriz=np.array(matriz)

In [12]:
np_matriz

array([[1, 3, 4],
       [6, 8, 3],
       [0, 5, 3]])

In [13]:
2*np_matriz

array([[ 2,  6,  8],
       [12, 16,  6],
       [ 0, 10,  6]])

In [14]:
mi_vector=np.array([4,7,9,2,5,6])

In [15]:
mi_vector

array([4, 7, 9, 2, 5, 6])

In [16]:
mi_vector2=np.array([4,5.0,True,"e"])

In [17]:
mi_vector2

array(['4', '5.0', 'True', 'e'], dtype='<U32')

In [18]:
mi_vector2=np.array([4,5.0,True,"e",(3,4)])

In [19]:
mi_vector2

array([4, 5.0, True, 'e', (3, 4)], dtype=object)

In [22]:
np_matriz.dtype

dtype('int32')

In [23]:
unos=np.ones((4,5))

In [24]:
unos

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
ceros=np.zeros((4,5))

In [26]:
ceros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
identidad5=np.identity(5)

In [28]:
identidad5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### shape

In [30]:
mi_vector.shape

(6,)

In [31]:
mi_vector

array([4, 7, 9, 2, 5, 6])

In [33]:
unos.shape

(4, 5)

In [34]:
unos

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
mi_vector2=np.array([[4, 7, 9, 2, 5, 6]])

In [37]:
mi_vector2

array([[4, 7, 9, 2, 5, 6]])

In [38]:
mi_vector2.shape

(1, 6)

## .reshape

In [40]:
unos.reshape((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
np.array([[2]])

array([[2]])

In [42]:
np.array([[2]]).shape

(1, 1)

In [43]:
np.array([2])

array([2])

In [44]:
np.array([2]).shape

(1,)

In [45]:
np.array([[2],[2]])

array([[2],
       [2]])

In [47]:
np.array([[2],[2]]).shape

(2, 1)

In [48]:
np.array([[2],[2,3]])

array([list([2]), list([2, 3])], dtype=object)

In [49]:
mi_vector

array([4, 7, 9, 2, 5, 6])

In [50]:
mi_vector.reshape((6,1))

array([[4],
       [7],
       [9],
       [2],
       [5],
       [6]])

In [51]:
mi_vector.reshape((1,6))

array([[4, 7, 9, 2, 5, 6]])

# astype

In [52]:
unos

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [53]:
unos.dtype

dtype('float64')

In [54]:

unos.astype("int32")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [56]:
np.array([1,2,3.0,True])

array([1., 2., 3., 1.])

In [58]:
np_matriz

array([[1, 3, 4],
       [6, 8, 3],
       [0, 5, 3]])

In [59]:
2*np_matriz

array([[ 2,  6,  8],
       [12, 16,  6],
       [ 0, 10,  6]])

In [60]:
2.5*np_matriz

array([[ 2.5,  7.5, 10. ],
       [15. , 20. ,  7.5],
       [ 0. , 12.5,  7.5]])

In [61]:
unos

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [62]:
unos.T

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [64]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [67]:
np.arange(1,21).reshape((5,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [69]:
np.arange(1,20).reshape((5,4))

ValueError: cannot reshape array of size 19 into shape (5,4)

In [70]:
mi_matriz2=np.arange(1,21).reshape((5,4))

In [71]:
mi_matriz2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [72]:
mi_matriz2+mi_matriz2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40]])

Operaciones elemento a elemento "element wise"

In [73]:
mi_matriz2*mi_matriz2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144],
       [169, 196, 225, 256],
       [289, 324, 361, 400]])

In [75]:
mi_matriz2.dot(mi_matriz2.T)

array([[  30,   70,  110,  150,  190],
       [  70,  174,  278,  382,  486],
       [ 110,  278,  446,  614,  782],
       [ 150,  382,  614,  846, 1078],
       [ 190,  486,  782, 1078, 1374]])

In [76]:
mi_matriz2.T

array([[ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19],
       [ 4,  8, 12, 16, 20]])

In [77]:
mi_matriz2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

## Slicing

In [78]:
mi_matriz3=np.arange(1,17).reshape((4,4))

In [79]:
mi_matriz3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [81]:
mi_matriz3[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [83]:
mi_matriz3[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [90]:
mi_matriz3[-1,1:]

array([14, 15, 16])

In [88]:
mi_matriz3[:][1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [89]:
mi_matriz3[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [91]:
mi_matriz3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [92]:
mi_matriz3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [95]:
mi_matriz3[range(1,mi_matriz3.shape[0],2),range(1,mi_matriz3.shape[1],2)]

array([ 6, 16])

In [94]:
[[6,8],[14,16]]

[[6, 8], [14, 16]]

In [99]:
list(range(1,mi_matriz3.shape[0],2))

[1, 3]

In [98]:
mi_matriz3[range(1,mi_matriz3.shape[0],2),:]

array([[ 5,  6,  7,  8],
       [13, 14, 15, 16]])

In [100]:
mi_matriz3[1::2,1::2]

array([[ 6,  8],
       [14, 16]])

# Ejercicio avanzado.

Seleccionar las 4 esquinas con slicing

Cálculo de la inversa y el determinante

In [111]:
mi_matriz3[0,0]=5

In [112]:
mi_matriz3

array([[ 5,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [113]:
np.linalg.inv(mi_matriz3)

array([[ 2.50000000e-01, -3.07692308e-01, -6.15384615e-01,
         1.53846154e-01],
       [-1.20000000e+00,  4.95395959e+15, -9.90791918e+15,
         4.95395959e+15],
       [ 1.65000000e+00, -9.90791918e+15,  1.98158384e+16,
        -9.90791918e+15],
       [-7.00000000e-01,  4.95395959e+15, -9.90791918e+15,
         4.95395959e+15]])

In [114]:
mi_matriz3.dot(np.linalg.inv(mi_matriz3)).astype(int)

array([[ 1,  0,  0,  0],
       [ 0, -8, 16,  0],
       [ 0, 16,  0,  0],
       [ 0,  0,  0,  0]])

In [115]:
np.linalg.det(mi_matriz3)

-3.2297397080004505e-15

# Indexado booleano

In [116]:
mi_vector

array([4, 7, 9, 2, 5, 6])

In [117]:
mi_vector==7

array([False,  True, False, False, False, False])

In [118]:
mi_vector>3

array([ True,  True,  True, False,  True,  True])

In [119]:
mi_matriz3>3

array([[ True, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [120]:
mi_matriz3

array([[ 5,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [122]:
mi_vector[[False,  True, False, False, False, False]]

array([7])

In [123]:
mi_vector[mi_vector>6]

array([7, 9])

In [124]:
mi_vector>6

array([False,  True,  True, False, False, False])

In [125]:
mi_vector[np.array([False,  True,  True, False, False, False])]

array([7, 9])

In [126]:
mi_matriz3

array([[ 5,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [128]:
mi_matriz3[mi_matriz3>8]

array([ 9, 10, 11, 12, 13, 14, 15, 16])

## Concatener arrays y matrices: axis

axis equivale a columnas o a filas.
axis toma 0 ó 1

axis 0 es filas y 1 columnas

In [129]:
mi_matriz2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [130]:
mi_matriz2.shape

(5, 4)

In [131]:
np.concatenate((mi_matriz2,mi_matriz2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [132]:
np.concatenate((mi_matriz2,mi_matriz2),axis=1)

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [13, 14, 15, 16, 13, 14, 15, 16],
       [17, 18, 19, 20, 17, 18, 19, 20]])

In [133]:
mi_matriz2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [137]:
mi_vector3=np.arange(40,45)
mi_vector3

array([40, 41, 42, 43, 44])

In [138]:
np.concatenate((mi_matriz2,mi_vector3),axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [139]:
print(mi_matriz2.shape)
print(mi_vector3.shape)

(5, 4)
(5,)


In [140]:
np.concatenate((mi_matriz2,mi_vector3.reshape(5,1)),axis=1)

array([[ 1,  2,  3,  4, 40],
       [ 5,  6,  7,  8, 41],
       [ 9, 10, 11, 12, 42],
       [13, 14, 15, 16, 43],
       [17, 18, 19, 20, 44]])

In [145]:
np.concatenate((mi_matriz2,mi_vector3[1:].reshape(1,4)),axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [41, 42, 43, 44]])

In [143]:
mi_matriz2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [146]:
mi_vector3

array([40, 41, 42, 43, 44])

In [147]:
mi_vector3[1:]

array([41, 42, 43, 44])

In [148]:
mi_vector3[1:].reshape(1,4)

array([[41, 42, 43, 44]])

Cómo generar números aleatorios


In [149]:
np.random.normal(0,1,(100,10))

array([[ 1.20859701e+00, -1.00174380e+00,  3.06728738e-01,
        -6.24189975e-02,  9.35609130e-01, -8.78627960e-01,
        -1.53724970e-01,  3.56686275e-01,  1.49120508e+00,
        -8.07757892e-01],
       [-4.33095070e-01, -2.49238220e-01, -8.91340041e-01,
        -1.27427882e+00,  1.05954647e+00, -3.47589426e-01,
         9.62500566e-01, -5.27654805e-01,  5.17514648e-01,
         1.47731251e+00],
       [ 4.74167912e-01, -1.38072907e-01,  6.29878672e-02,
         8.50953618e-01,  8.87417322e-01, -1.05617265e+00,
        -2.12977894e-01, -7.52874010e-01,  9.53582325e-01,
         6.85350783e-01],
       [ 6.78041349e-01, -8.50099157e-01,  5.49099046e-02,
        -3.52272512e-01, -1.57569059e+00, -1.52180265e+00,
         1.70596244e-01,  7.21372266e-01,  1.17945640e-02,
        -1.56803415e+00],
       [ 2.21474367e-02, -3.45717346e-01,  1.25047263e-01,
         7.69609602e-02,  7.68377477e-01,  3.54128747e-01,
         1.77147173e+00,  2.41605547e-01, -4.23470551e-01,
        -5.

In [150]:
np.random.randint(1,11,(100,10))

array([[ 4,  3,  2,  4, 10,  1, 10, 10,  5,  4],
       [ 9,  1,  1,  1,  9,  9,  7,  1,  1,  6],
       [ 5,  9,  2,  4,  3, 10,  1,  9,  9,  1],
       [ 8,  3,  2, 10,  1,  1,  4,  8,  6,  2],
       [ 8,  2,  6,  6,  9,  2,  5,  8,  2,  3],
       [ 8,  3,  7,  7,  9,  6,  3,  1,  3, 10],
       [ 7,  9,  5,  9,  1,  6,  7,  4,  2,  5],
       [ 3,  8,  2,  3,  4,  7,  6,  2,  9,  9],
       [ 5,  7,  8,  2,  4,  2,  1,  1,  4,  9],
       [ 5,  1,  3,  3,  5,  8,  5,  7,  3,  3],
       [10,  1,  7,  2, 10,  8,  2,  9,  2,  2],
       [ 1, 10,  3,  6,  5, 10,  1,  6,  8,  1],
       [ 5,  2,  6,  7, 10,  7,  9,  1,  8,  3],
       [ 9,  3, 10,  2, 10,  6,  5,  6,  8,  9],
       [ 3,  5,  1,  4,  8,  1,  5,  1, 10,  5],
       [ 3,  1,  1,  4,  9,  5,  2,  6,  5,  4],
       [ 1,  5,  4,  6,  9,  4,  3,  4,  9,  2],
       [10,  2,  3,  7,  5,  7,  4, 10,  3,  4],
       [10,  5,  1,  4,  8,  2,  3,  1,  3,  4],
       [ 8, 10,  3,  9,  8,  5,  9,  7,  4,  7],
       [ 2,  9,  3, 

In [152]:
matriz_normal=np.random.normal(0,1,(100,10))

In [153]:
matriz_normal.mean()

0.006996937032346945

In [154]:
matriz_normal.sum()

6.9969370323469455

In [155]:
matriz_normal.std()

1.0139598802942973

In [156]:
np.mean(matriz_normal)

0.006996937032346945

In [157]:
np.mean([1,2,3])

2.0

In [158]:
np.mean(matriz_normal,axis=0)

array([ 0.03417948, -0.13105921, -0.0010793 ,  0.03103256,  0.04586543,
       -0.00624217,  0.10515468, -0.00916756, -0.03795544,  0.0392409 ])

In [160]:
np.mean(matriz_normal,axis=1)

array([-0.5775488 ,  0.15673431,  0.61262432,  0.06076419, -0.57770003,
       -0.16160657, -0.37847028,  0.64062491,  0.12722781,  0.2481567 ,
       -0.09508191,  0.08533735, -0.12408129, -0.33297814,  0.11105831,
        0.37944489,  0.24184106,  0.09568066, -0.07300331, -0.48778463,
        0.12405942, -0.3089323 ,  0.15599506, -0.07479045, -0.4870033 ,
        0.15846453,  0.56451102, -0.53320071,  0.19457632, -0.32196017,
        0.09351269,  0.13793397,  0.08180371,  0.01520232, -0.02334905,
       -0.23955231,  0.15232971, -0.01132528, -0.01704968, -0.20417264,
       -0.09762541,  0.65824369,  0.56656774,  0.34253169,  0.06783736,
        0.03421666, -0.08057995,  0.16817822,  0.4475933 , -0.73130245,
        0.26431435,  0.71260247, -0.18256583, -0.3500355 , -0.19182757,
       -0.3378891 ,  0.00482303, -0.07332657, -0.28466949, -0.27885495,
        0.00081596,  0.32294351,  0.26013224, -0.22981946, -0.57146454,
        0.36326007,  0.08197896,  0.19678854,  0.35240476,  0.02

In [163]:
np.sum(matriz_normal,axis=0)

array([  3.41794781, -13.10592116,  -0.10793042,   3.10325646,
         4.58654325,  -0.62421709,  10.51546809,  -0.91675587,
        -3.79554421,   3.92409016])

In [162]:
sum(matriz_normal)

array([  3.41794781, -13.10592116,  -0.10793042,   3.10325646,
         4.58654325,  -0.62421709,  10.51546809,  -0.91675587,
        -3.79554421,   3.92409016])

In [164]:
np.log(8)

2.0794415416798357